<div class="row">
    <div id="map-canvas"/></div>
</div>
<style type="text/css">
div#container {
    width: 100%;
    max-width: 100%;
}
#map-canvas {
    width:100%;
    height:100%;
    min-height: 800px;
}
</style>
<script type="text/javascript">
    function initialize() {
        var mapOptions = {
            center: new google.maps.LatLng(<?php echo $centerLat; ?>, <?php echo $centerLon; ?>),
            zoom: 12,
            //mapTypeId: google.maps.MapTypeId.TERRAIN,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            backgroundColor: "#FFFFFF"
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

        var circle ={
            path: google.maps.SymbolPath.CIRCLE,
            fillColor: 'red',
            fillOpacity: .4,
            scale: 4.5,
            strokeColor: 'white',
            strokeWeight: 1
        };
        <?php foreach ($busstops as $busstop): ?>
            var marker = new google.maps.Marker({
            position: new google.maps.LatLng(<?php echo $busstop->getLatitude(); ?>, <?php echo $busstop->getLongitude(); ?>),
            map: map,
            icon: circle,
            title: '<?php echo addslashes($busstop->getName() . ', ' . $busstop->getTown()); ?>  (<?php echo addslashes($busstop->getCode()); ?>)'
        });
        <?php endforeach; ?>

        var customStyle = [
            { featureType: "administrative.country", elementType: "all", stylers: [{ visibility: "on", color: "#000000"}] },
            { featureType: "administrative.province", elementType: "all", stylers: [{ visibility: "off"}] },
            { featureType: "road", elementType: "all", stylers: [{ visibility: "on"}] },
            { featureType: "poi", elementType: "all", stylers: [{ visibility: "off"}] },
            { featureType: "landscape.natural.landcover", elementType: "all", stylers: [{ visibility: "off"}] },
            { featureType: "transit", elementType: "all", stylers: [{ visibility: "off"}] },
            { featureType: "transit.station", elementType: "all", stylers: [{ visibility: "on"}] },
            { featureType: "transit.station.rail", elementType: "all", stylers: [{ visibility: "on"}] },
            { featureType: "water", elementType: "all", stylers: [{ visibility: "on", color: "#ffcc3", hue: "#ffcc3"}] }
        ];
        var styledMapOptions = {
            name: "customStyle"
        };
        var customMapType = new google.maps.StyledMapType(customStyle, styledMapOptions);
        map.mapTypes.set('customStyle', customMapType);
        map.setMapTypeId('customStyle');
      }
      google.maps.event.addDomListener(window, 'load', initialize);
</script>
