<div class="row">
    <div class="col-xs-4">
        <div class="well well-sm">
            <?php echo $this->form()->openTag($form); ?>
            <div class="row">
                <div class="col-xs-4">
                    <b>Van</b>
                </div>
                <div class="col-xs-8">
                    <?php echo $this->formElement($form->get('busstopFrom')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <b>Naar</b>
                </div>
                <div class="col-xs-8">
                    <?php echo $this->formElement($form->get('busstopTo')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <button class="btn btn-success"><span class="glyphicon glyphicon-search"></span> Toon Route</button></br>
                     <?php echo $this->form()->closeTag($form); ?>
                </div>
            </div>
        </div>
            <table class="table">
                <tr><th>Vervoerder:</th><td><?php echo is_object($busstopFrom) ? $busstopFrom->getPto() : '';?></td></tr>
                <tr><th>Van:</th><td><?php echo is_object($busstopFrom) ? $busstopFrom->getName() . ', ' . $busstopFrom->getTown() . ' (' . $busstopFrom->getCode() . ')' : '';?></td></tr>
                <tr><th>Naar:</th><td><?php echo $busstopTo->getName() . ', ' . $busstopTo->getTown() . ' (' . $busstopTo->getCode() . ')';?></td></tr>
                <tr><th>Afstand:</th><td><?php echo number_format($distance, 2, ',', '.');?> meter</td></tr>
                <tr><th>Afstand Hemelsbreed:</th><td><?php echo number_format($flightDistance, 2, ',', '.');?> meter</td></tr>
                <tr><th>Afstanden per stop Hemelsbreed:</th><td><?php echo number_format($birdDistance, 2, ',', '.');?> meter</td></tr>
            </table>
    </div>
    <div class="col-xs-8">
        <div id="map-canvas"></div>
    </div>
</div>
<style type="text/css">
div#container {
    width: 100%;
    max-width: 100%;
}
#map-canvas {
    width:100%;
    height:100%;
    min-height: 750px;
}
</style>
<script type="text/javascript">
      function initialize() {
        var mapOptions = {
            center: new google.maps.LatLng(<?php echo $centerLat; ?>, <?php echo $centerLon; ?>),
            zoom: 13,
            scaleControl: true,
            mapTypeId: google.maps.MapTypeId.TERRAIN,
            backgroundColor: "#FFCC33"
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

        var circle ={
            path: google.maps.SymbolPath.CIRCLE,
            fillColor: 'red',
            fillOpacity: .4,
            scale: 4.5,
            strokeColor: 'white',
            strokeWeight: 1
        };

        <?php
            if (!is_null($path[0])):
                $queue = new \SplQueue;

                foreach ($path as $trainStation) {
                    $queue->enqueue($trainStation);
                    ?>
                    var marker = new google.maps.Marker({
                        position: new google.maps.LatLng(<?php echo $trainStation->getLatitude(); ?>, <?php echo $trainStation->getLongitude(); ?>),
                        map: map,
                        icon: circle,
                        title: '<?php echo addslashes($trainStation->getName() . ', ' . $trainStation->getTown()); ?>  (<?php echo addslashes($trainStation->getCode()); ?>)'
                    });
                    <?php
                }
                $from = $queue->dequeue();
                while ($queue->count() > 0) {
                    $to = $queue->dequeue();
                    ?>
                        var edge<?php echo str_replace(':', '', $from->getCode()); ?><?php echo str_replace(':', '', $to->getCode()); ?> = [
                            new google.maps.LatLng(<?php echo $from->getLatitude(); ?>, <?php echo $from->getLongitude(); ?>),
                            new google.maps.LatLng(<?php echo $to->getLatitude(); ?>, <?php echo $to->getLongitude(); ?>),
                        ];
                        var trackPath = new google.maps.Polyline({
                            path: edge<?php echo str_replace(':', '', $from->getCode()); ?><?php echo str_replace(':', '', $to->getCode()); ?>,
                            geodesic: true,
                            strokeColor: '#000066',
                            strokeOpacity: 1.0,
                            strokeWeight: 2
                        });

                        trackPath.setMap(map);
                    <?php
                    $from = $to;
                }
                endif;
            ?>

        var customStyle = [
            { featureType: "administrative.country", elementType: "all", stylers: [{ visibility: "on", color: "#000000"}] },
            { featureType: "administrative.province", elementType: "all", stylers: [{ visibility: "off"}] },
            { featureType: "road", elementType: "all", stylers: [{ visibility: "on"}] },
            { featureType: "poi", elementType: "all", stylers: [{ visibility: "off"}] },
            { featureType: "landscape.natural.landcover", elementType: "all", stylers: [{ visibility: "off"}] },
            { featureType: "transit", elementType: "all", stylers: [{ visibility: "off"}] },
            { featureType: "transit.station", elementType: "all", stylers: [{ visibility: "on"}] },
            { featureType: "transit.station.rail", elementType: "all", stylers: [{ visibility: "on"}] }
        ];
        var styledMapOptions = {
            name: "customStyle"
        };
        var customMapType = new google.maps.StyledMapType(customStyle, styledMapOptions);
        map.mapTypes.set('customStyle', customMapType);
        map.setMapTypeId('customStyle');
    };
    google.maps.event.addDomListener(window, 'load', initialize);
</script>