language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

script:
 - vendor/bin/phpunit -c phpunit.xml.dist

before_script:
 - composer selfupdate --quiet
 - composer install --no-interaction --prefer-source
