language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - nightly

script:
 - vendor/bin/phpunit

before_script:
 - composer selfupdate --quiet
 - composer install --no-interaction --prefer-source
