<?php

namespace Application\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-30 at 16:17:45.
 */
class MapControllerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var MapController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MapController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Application\Controller\MapController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Application\Controller\MapController::getEntityManager
     */
    public function testGetEntityManager()
    {
        $mock = $this->getMock('\Zend\ServiceManager\ServiceManager');
        $mock
            ->expects($this->any())
            ->method('get')
            ->will($this->returnValue('EntityManager'));
        $this->object->setServiceLocator($mock);
        $this->assertEquals('EntityManager', $this->object->getEntityManager());

        $value = 'entityManager';
        //$this->assertNull($this->object->getEntityManager());
        $this->object->setEntityManager($value);
        $this->assertSame($value, $this->object->getEntityManager());
    }

    /**
     * @covers Application\Controller\MapController::setEntityManager
     */
    public function testSetEntityManager()
    {
        $value = 'entityManager';
        $this->assertSame($this->object, $this->object->setEntityManager($value));
    }

}
