<?php

namespace Application\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-12-15 at 11:24:13.
 */
class TrackTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Track
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Track;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Application\Entity\Track::getLeftBusStop
     */
    public function testGetLeftBusStop()
    {
        $value = 'leftStop';
        $this->assertNull($this->object->getLeftBusStop());
        $this->object->setLeftBusStop($value);
        $this->assertEquals($value, $this->object->getLeftBusStop());
    }

    /**
     * @covers Application\Entity\Track::setLeftBusStop
     */
    public function testSetLeftBusStop()
    {
        $this->assertEquals($this->object, $this->object->setLeftBusStop('left stop'));
    }

    /**
     * @covers Application\Entity\Track::getRightBusStop
     */
    public function testGetRightBusStop()
    {
        $value = 'leftStop';
        $this->assertNull($this->object->getRightBusStop());
        $this->object->setRightBusStop($value);
        $this->assertEquals($value, $this->object->getRightBusStop());
    }

    /**
     * @covers Application\Entity\Track::setRightBusStop
     */
    public function testSetRightBusStop()
    {
        $this->assertEquals($this->object, $this->object->setRightBusStop('right stop'));
    }

    /**
     * @covers Application\Entity\Track::getDistance
     */
    public function testGetDistance()
    {
        $value = 20;
        $this->assertNull($this->object->getDistance());
        $this->object->setDistance($value);
        $this->assertEquals($value, $this->object->getDistance());
    }

    /**
     * @covers Application\Entity\Track::setDistance
     */
    public function testSetDistance()
    {
        $this->assertEquals($this->object, $this->object->setDistance(32));
    }

    /**
     * @covers Application\Entity\Track::getPto
     */
    public function testGetPto()
    {
        $value = 'HTM';
        $this->assertNull($this->object->getPto());
        $this->object->setPto($value);
        $this->assertEquals($value, $this->object->getPto());
    }

    /**
     * @covers Application\Entity\Track::setPto
     */
    public function testSetPto()
    {
        $this->assertEquals($this->object, $this->object->setPto('HTM'));
    }
}
