<?php

namespace Application\Math;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-12-15 at 12:27:08.
 */
class CoordinateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Coordinate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Coordinate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Application\Math\Coordinate::haversineGreatCircleDistance
     */
    public function testHaversineGreatCircleDistance()
    {
        $this->assertEquals(
            (string) 21988.88835545,
            (string) $this->object->haversineGreatCircleDistance(52.1490617, 5.366273, 52.056364, 5.081895)
        );
    }
}
